Repository J1P5/Meerket_FE, pull requests merged in 2024-12, with the labels that each got.

#174 chore: Router 설정
  src/App.tsx
  src/pages/BlockedUsersPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/ChatListPage.tsx
  src/pages/ChatRoomPage.tsx
  src/pages/DetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MarketPricePage.tsx
  src/pages/MyPage.tsx
  src/pages/NeighborhoodAuthPage.tsx
  src/pages/NeighborhoodSelectionPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/PermissionRequestPage.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/ProfileRegistrationPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/SelectLocationPage.tsx
  src/pages/TransactionLocationPage.tsx
  src/pages/TransactionPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ⚙ Setting, ✨ Feature

#184 feat: PostRegisterForm 컴포넌트 개발
  src/components/atoms/Button/IconButton/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/Input/stories.tsx
  src/components/atoms/Input/styled.ts
  src/components/atoms/Select/styled.ts
  src/components/atoms/Textarea/index.tsx
  src/components/molecules/LabeledInput/index.tsx
  src/components/molecules/LabeledTextarea/index.tsx
  src/components/organisms/PostImageManager/index.tsx
  src/components/organisms/PostImageManager/stories.tsx
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/PostRegisterForm/stories.tsx
  src/components/organisms/PostRegisterForm/styled.ts
  src/components/organisms/index.ts
  src/types/image.d.ts
  src/types/index.ts
  src/types/post.d.ts
Labels: organism

#172 chore: axios instance 생성
  package.json
  src/services/api.ts
  src/types/index.ts
  src/types/response/index.ts
  src/types/response/response.d.ts
  yarn.lock
Labels: 📬 API

#194 feat: HomeTemplate 컴포넌트 개발
  src/components/organisms/BottomNavBar/styled.ts
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/EmptyTemplate/stories.ts
  src/components/templates/EmptyTemplate/styled.ts
  src/components/templates/HomeTemplate/index.tsx
  src/components/templates/HomeTemplate/stories.ts
  src/components/templates/HomeTemplate/styled.ts
Labels: template

#196 feat: TransactionLocationTemplate 컴포넌트 개발
  src/components/organisms/Map/index.tsx
  src/components/organisms/Map/stories.tsx
  src/components/organisms/Map/styled.ts
  src/components/templates/TransactionLocationTemplate/index.tsx
  src/components/templates/TransactionLocationTemplate/stories.tsx
  src/components/templates/TransactionLocationTemplate/styled.ts
  src/components/templates/index.ts
  src/hooks/useMap.ts
  src/types/map.d.ts
Labels: template

#198 feat: RootLayout 컴포넌트 개발
  src/App.tsx
  src/components/atoms/Icon/styled.ts
  src/components/organisms/BottomNavBar/index.tsx
  src/components/organisms/BottomNavBar/styled.ts
  src/components/organisms/TopBar/index.tsx
  src/components/organisms/TopBar/styled.ts
  src/components/templates/RootLayout/index.tsx
  src/components/templates/RootLayout/styled.ts
  src/components/templates/index.ts
  src/constants/bottomNavItems.ts
  src/hooks/index.ts
  src/hooks/useSearchTopBar.ts
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SearchResultPage.tsx
  src/router.tsx
  src/stores/headerStore.ts
  src/stores/index.ts
  src/stores/topbarStore.ts
  src/styles/global.tsx
  src/styles/index.ts
Labels: ✨ Feature, 🎨 Html&css

#200 feat: SearchResultsTemplate 컴포넌트 개발
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/SearchResultsTemplate/index.tsx
  src/components/templates/SearchResultsTemplate/stories.ts
  src/components/templates/SearchResultsTemplate/styled.ts
Labels: template

#199 feat: SearchTemplate 컴포넌트 개발
  src/components/organisms/SearchHistory/index.tsx
  src/components/templates/SearchTemplate/index.tsx
  src/components/templates/SearchTemplate/stories.ts
  src/components/templates/SearchTemplate/styled.ts
Labels: template

#197 feat: CategoryTemplate 컴포넌트 개발
  src/components/templates/CategoryTemplate/index.tsx
  src/components/templates/CategoryTemplate/stories.ts
  src/components/templates/CategoryTemplate/styled.ts
  src/components/templates/HomeTemplate/index.tsx
  src/components/templates/HomeTemplate/styled.ts
  src/components/templates/MarketPriceTemplate/index.tsx
  src/components/templates/MarketPriceTemplate/styled.ts
Labels: template

#201 feat: TransactionTemplate 컴포넌트 개발
  src/components/templates/TransactionBuyTemplate/index.tsx
  src/components/templates/TransactionBuyTemplate/stories.ts
  src/components/templates/TransactionBuyTemplate/styled.ts
  src/components/templates/TransactionSellTemplate/index.tsx
  src/components/templates/TransactionSellTemplate/stories.tsx
  src/components/templates/TransactionSellTemplate/styled.ts
Labels: template

#203 feat: FCM 연동
  index.html
  package.json
  public/firebase-messaging-sw.js
  src/App.tsx
  src/hooks/index.ts
  src/hooks/useForegroundNotification.ts
  src/hooks/usePermission.ts
  src/pages/PermissionRequestPage.tsx
  src/services/firebase.ts
  yarn.lock
Labels: ✨ Feature

#204 feat: MyPageTemplate 컴포넌트 개발
  src/components/templates/MyPageTemplate/index.tsx
  src/components/templates/MyPageTemplate/stories.tsx
  src/components/templates/MyPageTemplate/styled.ts
Labels: template

#207 feat: PermissionRequestTemplate 컴포넌트 개발
  src/components/organisms/PermissionList/styled.ts
  src/components/templates/PermissionRequestTemplate/index.tsx
  src/components/templates/PermissionRequestTemplate/stories.ts
  src/components/templates/PermissionRequestTemplate/styled.ts
  src/components/templates/RootLayout/styled.ts
Labels: template

#208 feat: ChatListTemplate 컴포넌트 변경
  src/components/organisms/ChatOverview/styled.ts
  src/components/templates/ChatListTemplate/index.tsx
  src/components/templates/ChatListTemplate/stories.ts
Labels: 🔨 Refactor, template

#209 feat: LoginTemplate 컴포넌트 개발
  src/components/atoms/Button/LoginButton/styled.ts
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/LoginTemplate/stories.tsx
  src/components/templates/LoginTemplate/styled.ts
Labels: template

#211 fix: TopBar 표시되는 페이지 수정
  src/components/templates/RootLayout/index.tsx
Labels: 🐞 BugFix

#214 feat: ProfileRegistrationTemplate 컴포넌트 개발
  src/components/templates/ProfileRegistrationTemplate/index.tsx
Labels: template

#219 feat: BlockedUsersTemplate 컴포넌트 개발
  src/components/organisms/BlockedUserItem/index.tsx
  src/components/organisms/BlockedUsersList/index.tsx
  src/components/organisms/BlockedUsersList/stories.ts
  src/components/organisms/BlockedUsersList/styled.ts
  src/components/templates/BlockedUsersTemplate/index.tsx
  src/components/templates/BlockedUsersTemplate/stories.tsx
  src/components/templates/BlockedUsersTemplate/styled.ts
  src/types/index.ts
  src/types/profile.d.ts
Labels: template

#216 fix: TopBar 수정
  src/components/atoms/Icon/NoIcon/index.tsx
  src/components/atoms/Icon/NoIcon/stories.ts
  src/components/atoms/Icon/NoIcon/styled.ts
  src/components/atoms/Icon/index.ts
  src/components/organisms/TopBar/index.tsx
  src/components/organisms/TopBar/stories.tsx
  src/components/organisms/TopBar/styled.ts
  src/components/templates/RootLayout/index.tsx
  src/hooks/useSearchTopBar.ts
  src/stores/topbarStore.ts
Labels: 🎨 Html&css, 🐞 BugFix

#218 fix: Axios Instance 수정
  src/services/api.ts
  src/services/apis/example.ts
  src/services/apis/index.ts
  src/types/response/example.d.ts
  src/types/response/index.ts
Labels: 🐞 BugFix, 📬 API

#230 feat: DetailTemplate 컴포넌트 개발
  src/components/organisms/AuctionControlBar/styled.ts
  src/components/templates/DetailTemplate/index.tsx
  src/components/templates/DetailTemplate/stories.tsx
  src/components/templates/DetailTemplate/styled.ts
Labels: template

#232 feat: PostRegisterTemplate 컴포넌트 개발
  src/components/atoms/Input/index.tsx
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/PostRegisterForm/styled.ts
  src/components/templates/PostRegisterTemplate/index.tsx
  src/components/templates/PostRegisterTemplate/stories.tsx
  src/components/templates/PostRegisterTemplate/styled.ts
  src/constants/categories.ts
  src/constants/options.ts
  src/types/category.d.ts
  src/types/index.ts
Labels: template

#242 feat: NeighborhoodSelectionTemplate 컴포넌트 개발
  src/components/templates/NeighborhoodSelectionTemplate/index.tsx
  src/components/templates/NeighborhoodSelectionTemplate/stories.tsx
  src/components/templates/NeighborhoodSelectionTemplate/styled.ts
  src/components/templates/RootLayout/index.tsx
  src/hooks/index.ts
  src/hooks/useNeighborhoodSelection.ts
Labels: template

#252 fix: #222 이슈 관련 빌드 에러 수정
  src/components/organisms/BlockedUserItem/stories.ts
  src/components/templates/MyPageTemplate/stories.tsx
  src/hooks/useWebSocket.ts
  src/utils/security.ts
Labels: 🌏 Deploy, 🐞 BugFix

#254 feat: 로그인 페이지 개발
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/components/organisms/ProfileRegistrationForm/stories.tsx
  src/components/templates/ProfileRegistrationTemplate/stories.tsx
  src/pages/LoginPage.tsx
  src/pages/OAuthCallbackPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/services/api.ts
  src/services/apis/auth.ts
  src/services/apis/index.ts
  src/stores/index.ts
  src/stores/userStore.ts
  src/types/response/auth.d.ts
  src/types/response/index.ts
  src/types/user.d.ts
Labels: ✨ Feature

#256 feat: 프로필 등록 페이지 개발
  src/assets/ProfileRegistrationForm/profile_upload.svg
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/components/organisms/ProfileRegistrationForm/styled.ts
  src/pages/ProfileRegistrationPage.tsx
  src/services/apis/index.ts
  src/services/apis/user.ts
  src/stores/userStore.ts
  src/types/response/index.ts
  src/types/response/user.d.ts
Labels: ✨ Feature

#261 feat: 상세페이지 개발 (1차)
  src/components/molecules/ImageSlider/styled.ts
  src/components/molecules/KebabMenu/index.tsx
  src/components/molecules/KebabMenu/stories.tsx
  src/components/molecules/ModalBottomSheet/styled.ts
  src/components/organisms/AuctionControlBar/index.tsx
  src/components/organisms/AuctionControlBar/stories.tsx
  src/components/organisms/AuctionTimer/index.tsx
  src/components/organisms/AuctionTimer/styled.ts
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Comment/stories.ts
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/CommentItem/stories.ts
  src/components/organisms/CommentItem/styled.ts
  src/components/organisms/ItemDetails/index.tsx
  src/components/organisms/ItemDetails/styled.ts
  src/components/organisms/LocationMap/index.tsx
  src/components/organisms/LocationMap/styled.ts
  src/components/organisms/Modal/styled.ts
  src/components/templates/DetailTemplate/index.tsx
  src/components/templates/DetailTemplate/stories.tsx
  src/components/templates/RootLayout/styled.ts
  src/constants/auctionControlBarNames.ts
  src/constants/modalMessage.ts
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useBid.tsx
  src/hooks/useCommentKebabMenuManager.ts
  src/hooks/useCommentWriter.ts
  src/hooks/useDetailModal.tsx
  src/hooks/useFetchProduct.ts
  src/hooks/useKebabMenu.ts
  src/pages/DetailPage.tsx
  src/services/api.ts
  src/services/apis/comment.ts
  src/services/apis/index.ts
  src/services/apis/product.ts
  src/types/menu.d.ts
  src/types/response/comment.d.ts
  src/types/response/index.ts
  src/types/response/product.d.ts
Labels: ✨ Feature

#268 feat: 동네 선택 페이지 개발
  src/components/organisms/TopBar/styled.ts
  src/components/templates/NeighborhoodSelectionTemplate/index.tsx
  src/components/templates/NeighborhoodSelectionTemplate/stories.tsx
  src/hooks/useNeighborhoodSelection.ts
  src/pages/NeighborhoodSelectionPage.tsx
  src/services/apis/activityAreas.ts
  src/services/apis/index.ts
  src/types/response/activityAreas.d.ts
  src/types/response/index.ts
Labels: ✨ Feature, 📬 API

#281 feat: 상세페이지 개발 (2차)
  src/components/organisms/CommentItem/index.tsx
  src/components/templates/DetailTemplate/index.tsx
  src/components/templates/DetailTemplate/stories.tsx
  src/hooks/index.ts
  src/hooks/useCommentWriter.ts
  src/hooks/useFetchComment.ts
  src/hooks/useFetchProduct.ts
  src/pages/DetailPage.tsx
  src/pages/DetailPage/index.tsx
  src/pages/DetailPage/styled.ts
  src/services/apis/comment.ts
  src/services/apis/product.ts
  src/types/response/product.d.ts
Labels: ✨ Feature, 📬 API

#282 chore: CategoryGrid 디자인 적용
  src/assets/LoginButton/kakao.svg
  src/assets/Map/default_marker.svg
  src/assets/Map/my_marker.svg
  src/assets/ProfileRegistrationForm/profile_upload.svg
  src/components/atoms/Icon/ChatIcon/index.tsx
  src/components/atoms/Icon/HomeIcon/index.tsx
  src/components/atoms/Icon/MarketPriceIcon/index.tsx
  src/components/atoms/Icon/MyPageIcon/index.tsx
  src/components/atoms/Icon/SendIcon/index.tsx
  src/components/atoms/Icon/styled.ts
  src/components/atoms/Sticker/index.tsx
  src/components/atoms/Sticker/stories.ts
  src/components/atoms/Sticker/styled.ts
  src/components/molecules/NavBarItem/index.tsx
  src/components/organisms/BottomNavBar/styled.ts
  src/components/organisms/CategoryGrid/index.tsx
  src/components/organisms/CategoryGrid/stories.ts
  src/components/templates/CategoryTemplate/stories.ts
  src/components/templates/CategoryTemplate/styled.ts
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/EmptyTemplate/styled.ts
  src/components/templates/HomeTemplate/styled.ts
  src/components/templates/MarketPriceTemplate/index.tsx
  src/components/templates/MarketPriceTemplate/styled.ts
  src/components/templates/SearchResultsTemplate/styled.ts
  src/components/templates/SearchTemplate/index.tsx
  src/components/templates/SearchTemplate/styled.ts
  src/pages/CategoryPage.tsx
  src/pages/MarketPricePage.tsx
  src/pages/SearchResultPage.tsx
  src/stories/assets/accessibility.svg
  src/stories/assets/discord.svg
  src/stories/assets/tutorials.svg
  src/types/category.d.ts
  src/types/post.d.ts
Labels: 🎨 Html&css

#285 chore: 버튼 사이즈 통일 디자인 작업
  src/components/atoms/Button/LoginButton/styled.ts
  src/components/atoms/Icon/LocationIcon/index.tsx
  src/components/organisms/NeighborhoodSelectionList/index.tsx
  src/components/organisms/NeighborhoodSelectionList/styled.ts
  src/components/organisms/ProfileRegistrationForm/styled.ts
  src/components/organisms/TransactionOverview/styled.ts
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/NeighborhoodSelectionTemplate/index.tsx
  src/components/templates/NeighborhoodSelectionTemplate/styled.ts
  src/pages/ChatRoomPage.tsx
Labels: 🎨 Html&css

#287 feat: 댓글 디자인 적용
  src/components/atoms/Icon/ReplyIcon/index.tsx
  src/components/atoms/Icon/ReplyIcon/stories.ts
  src/components/atoms/Icon/index.ts
  src/components/molecules/InputWithButton/index.tsx
  src/components/molecules/KebabMenu/index.tsx
  src/components/molecules/KebabMenu/styled.ts
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Comment/stories.tsx
  src/components/organisms/Comment/styled.ts
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/CommentItem/stories.tsx
  src/components/organisms/CommentItem/styled.ts
  src/components/templates/DetailTemplate/styled.ts
Labels: 🎨 Html&css

#288 feat: 로그인 / 프로필 등록 백엔드 연동
  src/pages/OAuthCallbackPage.tsx
  src/pages/ProfileRegistrationPage.tsx
  src/services/apis/user.ts
  src/stores/userStore.ts
  src/types/response/auth.d.ts
  src/types/response/user.d.ts
  src/types/user.d.ts
Labels: 📬 API

#290 feat: 상세 페이지 작업 (3차)
  src/components/atoms/Button/TextButton/index.tsx
  src/components/atoms/Button/TextButton/styled.ts
  src/components/atoms/Icon/ReplyIcon/index.tsx
  src/components/organisms/AuctionBidBottomSheet/index.tsx
  src/components/organisms/AuctionBidBottomSheet/styled.ts
  src/components/organisms/AuctionControlBar/index.tsx
  src/components/organisms/AuctionControlBar/styled.ts
  src/components/organisms/AuctionTimer/index.tsx
  src/components/organisms/AuctionTimer/styled.ts
  src/components/organisms/ItemDetails/index.tsx
  src/components/organisms/ItemDetails/styled.ts
  src/components/organisms/LocationMap/index.tsx
  src/components/organisms/LocationMap/styled.ts
  src/components/templates/DetailTemplate/index.tsx
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useBid.tsx
  src/hooks/useFetchBidding.ts
  src/pages/DetailPage/index.tsx
  src/services/apis/auction.ts
  src/services/apis/index.ts
  src/services/apis/product.ts
  src/types/response/auction.d.ts
  src/types/response/index.ts
  src/types/response/product.d.ts
Labels: 🎨 Html&css, 📬 API

#292 feat: RouterGuard 적용
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/components/organisms/ProfileRegistrationForm/stories.tsx
  src/components/templates/ProfileRegistrationTemplate/stories.tsx
  src/hooks/useNeighborhoodSelection.ts
  src/pages/OAuthCallbackPage.tsx
  src/pages/ProfileRegistrationPage.tsx
  src/pages/guards/AuthGuard.tsx
  src/pages/guards/LoginGuard.tsx
  src/pages/guards/index.ts
  src/router.tsx
  src/services/apis/activityAreas.ts
  src/services/apis/user.ts
  src/stores/userStore.ts
  src/types/response/user.d.ts
  src/types/user.d.ts
Labels: ✨ Feature

#293 feat: PostRegisterPage 컴포넌트 개발 (3차)
  src/components/atoms/Icon/CameraIcon/index.tsx
  src/components/atoms/Icon/CameraIcon/stories.ts
  src/components/atoms/Icon/index.ts
  src/components/atoms/ImageUpload/styled.ts
  src/components/atoms/Input/styled.ts
  src/components/atoms/Label/styled.ts
  src/components/atoms/Select/styled.ts
  src/components/atoms/Textarea/styled.ts
  src/components/molecules/UploadedImageCounter/index.tsx
  src/components/molecules/UploadedImageCounter/styled.ts
  src/components/organisms/LocationInputBottomSheet/index.tsx
  src/components/organisms/LocationInputBottomSheet/stories.tsx
  src/components/organisms/LocationInputBottomSheet/styled.ts
  src/components/organisms/PostImageItem/index.tsx
  src/components/organisms/PostImageItem/styled.ts
  src/components/organisms/PostImageManager/index.tsx
  src/components/organisms/PostImageManager/styled.ts
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/PostRegisterForm/styled.ts
  src/components/templates/SelectLocationTemplate/index.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/SelectLocationPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#295 fix: RouterGuard 제거
  src/pages/guards/AuthGuard.tsx
  src/pages/guards/LoginGuard.tsx
Labels: 🐞 BugFix

#297 fix: 활동 동네 설정 수정
  src/hooks/useNeighborhoodSelection.ts
Labels: 🐞 BugFix

#298 fix: 흐름에 맞게 수정
  src/hooks/useNeighborhoodSelection.ts
  src/pages/ProfileRegistrationPage.tsx
Labels: 🐞 BugFix

#300 feat: 상세 페이지 (4차)
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Comment/stories.tsx
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/CommentItem/styled.ts
  src/components/templates/DetailTemplate/styled.ts
  src/constants/modalMessage.ts
  src/hooks/index.ts
  src/hooks/useBid.ts
  src/hooks/useDetailModal.ts
  src/hooks/useModalForm.tsx
  src/pages/DetailPage/index.tsx
  src/types/response/comment.d.ts
Labels: ✨ Feature

#303 feat: NeighborhoodAuthPage 컴포넌트 개발 (최종)
  src/hooks/useNeighborhoodSelection.ts
  src/pages/NeighborhoodAuthPage.tsx
  src/services/apis/areaAuth.ts
  src/services/apis/index.ts
  src/stores/userStore.ts
  src/types/response/areaAuth.d.ts
  src/types/response/index.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#305 feat: PostRegisterPage 컴포넌트 개발 (3차)
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/templates/PostRegisterTemplate/index.tsx
  src/pages/PostRegisterPage.tsx
  src/services/apis/product.ts
  src/stores/formDataStore.ts
  src/types/post.d.ts
  src/types/response/product.d.ts
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, 🥰 Accessibility

#309 feat: 상세페이지 작업 (5차)
  src/hooks/useBid.ts
  src/pages/DetailPage/index.tsx
  src/pages/DetailPage/styled.ts
Labels: 🐞 BugFix

#310 feat: RouteGuard 적용
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useFetchSession.ts
  src/pages/guards/AuthGuard.tsx
  src/pages/guards/LoginGuard.tsx
  src/pages/guards/RequiredGuard.tsx
  src/pages/guards/index.ts
  src/router.tsx
  src/services/apis/user.ts
  src/types/response/user.d.ts
Labels: ✨ Feature, 📬 API

#311 fix: 닉네임 중복확인 처리
  src/components/atoms/Toast/styled.ts
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/pages/ProfileRegistrationPage.tsx
Labels: 🐞 BugFix

#313 feat: 상세페이지 작업 (5차)
  src/components/atoms/Toast/styled.ts
  src/components/templates/DetailTemplate/index.tsx
  src/components/templates/DetailTemplate/stories.tsx
  src/components/templates/DetailTemplate/styled.ts
  src/hooks/useBid.ts
  src/hooks/useFetchProduct.ts
  src/pages/DetailPage/index.tsx
  src/types/response/product.d.ts
Labels: ✨ Feature

#317 feat: 상세페이지 작업 (7차)
  src/components/atoms/Button/TextButton/index.tsx
  src/components/organisms/AuctionControlBar/styled.ts
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Comment/stories.tsx
  src/components/organisms/Comment/styled.ts
  src/components/organisms/CommentItem/deleted.tsx
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/CommentItem/styled.ts
  src/components/templates/DetailTemplate/index.tsx
  src/hooks/useBid.ts
  src/hooks/useCommentWriter.ts
  src/pages/DetailPage/index.tsx
  src/services/apis/product.ts
  src/types/response/comment.d.ts
Labels: ✨ Feature

#319 fix: RouterGuard 수정
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/pages/guards/AuthGuard.tsx
Labels: 🐞 BugFix

#320 fix: session 가져올 때 에러나면 user 데이터 null
  src/hooks/useFetchSession.ts
  src/pages/guards/AuthGuard.tsx
Labels: 🐞 BugFix

#322 fix: 디자인 어색한부분 수정
  src/components/organisms/Modal/styled.ts
  src/components/organisms/TopBar/styled.ts
Labels: 🎨 Html&css, 🐞 BugFix

#332 feat: 상세페이지 작업 (8차)
  src/components/organisms/CommentItem/index.tsx
  src/constants/modalMessage.ts
  src/hooks/useDetailModal.ts
  src/hooks/useFetchProduct.ts
  src/pages/DetailPage/index.tsx
Labels: ✨ Feature

#335 feat: 상세페이지 작업 (9차 - 조기마감)
  src/components/templates/DetailTemplate/index.tsx
Labels: ✨ Feature

#339 fix: TopBar Input쪽 수정
  src/components/organisms/TopBar/index.tsx
  src/components/templates/RootLayout/index.tsx
  src/hooks/useNeighborhoodSelection.ts
  src/hooks/useSearchTopBar.ts
  src/pages/NeighborhoodSelectionPage.tsx
  src/stores/topbarStore.ts
Labels: ✨ Feature, 🐞 BugFix

#345 feat: 상세페이지 작업 (10차)
  src/components/organisms/AuctionTimer/index.tsx
  src/components/templates/DetailTemplate/index.tsx
  src/hooks/useFetchProduct.ts
  src/hooks/useRemainingTimer.ts
  src/pages/DetailPage/index.tsx
  src/utils/dayFormatter.ts
Labels: ✨ Feature

#350 feat: 구매내역 API 연동 (1차)
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useFetchTransactions.ts
  src/pages/TransactionPage.tsx
  src/services/apis/index.ts
  src/services/apis/transaction.ts
  src/types/response/index.ts
  src/types/response/transaction.d.ts
Labels: ✨ Feature, 📬 API

#354 feat: MarketPricePage 컴포넌트 개발
  src/components/templates/EmptyTemplate/index.tsx
  src/constants/HomePageConstants.ts
  src/constants/MarketPricePageConstants.ts
  src/pages/HomePage.tsx
  src/pages/MarketPricePage.tsx
Labels: ✨ Feature, 📬 API

#359 feat: 판매내역 API 연동 (2차)
  src/components/organisms/PostItem/index.tsx
  src/pages/TransactionPage.tsx
Labels: ✨ Feature

#360 feat: 20억 초과 입력 시 처리
  src/components/organisms/AuctionBidBottomSheet/index.tsx
  src/components/organisms/AuctionBidBottomSheet/styled.ts
  src/components/organisms/PostRegisterForm/index.tsx
Labels: ✨ Feature, 🐞 BugFix

#362 fix: 상세페이지 에러 수정
  src/hooks/useFetchProduct.ts
Labels: 🐞 BugFix

#349 chore: PWA 적용
  index.html
  public/icons/AppIcon.svg
  public/icons/logo-128x128.png
  public/icons/logo-192x192.png
  public/icons/logo-512x512.png
  public/icons/logo-64x64.png
  public/manifest.json
  public/sw.js
Labels: ⚙ Setting

#364 feat: 채팅방 API 거래 완료 여부 추가
  src/components/atoms/Button/TextButton/index.tsx
  src/components/atoms/Button/TextButton/styled.ts
  src/components/organisms/PostItem/index.tsx
  src/components/organisms/PostItem/styled.ts
  src/components/organisms/PostList/index.tsx
  src/components/templates/ChatRoomTemplate/TopSheet.tsx
  src/components/templates/TransactionSellTemplate/index.tsx
  src/pages/ChatRoomPage.tsx
Labels: ✨ Feature, 📬 API

#367 feat: 개인정보 처리 방침 및 서비스 이용 약관 Page 및 Template 추가
  public/privacy-policy.html
  public/terms-of-service.html
  src/components/organisms/PostList/index.tsx
  src/components/templates/PrivacyPolicyTemplate/index.tsx
  src/components/templates/PrivacyPolicyTemplate/stories.ts
  src/components/templates/PrivacyPolicyTemplate/styled.ts
  src/components/templates/TermsOfServiceTemplate/index.tsx
  src/components/templates/TermsOfServiceTemplate/stories.ts
  src/components/templates/TermsOfServiceTemplate/styled.ts
  src/components/templates/index.ts
  src/constants/PrivacyPolicyPageConstants.ts
  src/constants/TermsOfServicePageConstants.ts
  src/constants/myPageMenus.ts
  src/pages/ChatRoomPage.tsx
  src/pages/PrivacyPolicyPage.tsx
  src/pages/TermsOfServicePage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: 📬 API, template

#376 deploy: manifest.json 권장 옵션 추가
  public/manifest.json
  public/screenshot/screenshot1.jpg
  public/screenshot/screenshot2.jpg
Labels: 🌏 Deploy

#373 feat: 신고하기 API 연동
  src/components/organisms/Comment/index.tsx
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/PostItem/index.tsx
  src/constants/modalMessage.ts
  src/hooks/useDetailModal.ts
  src/pages/DetailPage/index.tsx
  src/services/apis/user.ts
  src/types/response/comment.d.ts
  src/types/user.d.ts
Labels: ✨ Feature, 📬 API

#386 refactor: 로그인 콜백 경로일 경우 로그인 템플릿을 보여주지 않도록 변경
  src/pages/LoginPage.tsx
Labels: 🔨 Refactor

#389 feat: 차단 기능 API 연동
  package.json
  src/components/organisms/BlockedUserItem/index.tsx
  src/components/organisms/BlockedUserItem/stories.ts
  src/components/organisms/BlockedUserItem/styled.ts
  src/components/organisms/BlockedUsersList/stories.ts
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Comment/stories.tsx
  src/components/organisms/CommentItem/blocked.tsx
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/templates/BlockedUsersTemplate/index.tsx
  src/components/templates/BlockedUsersTemplate/stories.tsx
  src/components/templates/BlockedUsersTemplate/styled.ts
  src/constants/modalMessage.ts
  src/constants/myPageMenus.ts
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useDetailModal.ts
  src/hooks/useFetchBlockedUsers.ts
  src/pages/BlockedUsersPage.tsx
  src/pages/DetailPage/index.tsx
  src/services/apis/block.ts
  src/services/apis/index.ts
  src/types/block.d.ts
  src/types/index.ts
  src/types/profile.d.ts
  src/types/response/block.d.ts
  src/types/response/comment.d.ts
  src/types/response/index.ts
  yarn.lock
Labels: 📬 API

#390 feat: 차단 기능 API 연동 (2차)
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/CommentItem/styled.ts
  src/hooks/useFetchBlockedUsers.ts
  src/pages/BlockedUsersPage.tsx
Labels: 📬 API

#392 fix: 구글 심사 관련 에셋링크 문제 해결
  public/.well-known/assetlinks.json
Labels: 🌏 Deploy
