Repository J1P5/Meerket_FE, pull requests merged in 2025-02, with the labels that each got.

#457 refactor: 동네 설정 페이지 최적화 작업
  README.md
  index.html
  package.json
  src/components/atoms/Icon/BackIcon/index.tsx
  src/components/atoms/Icon/BanIcon/index.tsx
  src/components/atoms/Icon/BuyIcon/index.tsx
  src/components/atoms/Icon/DownIcon/index.tsx
  src/components/atoms/Icon/HistoryIcon/index.tsx
  src/components/atoms/Icon/KebabIcon/index.tsx
  src/components/atoms/Icon/LinkIcon/index.tsx
  src/components/atoms/Icon/LocationIcon/index.tsx
  src/components/atoms/Icon/MyLocationIcon/index.tsx
  src/components/atoms/Icon/NextIcon/index.tsx
  src/components/atoms/Icon/NotificationIcon/index.tsx
  src/components/atoms/Icon/PlusIcon/index.tsx
  src/components/atoms/Icon/SearchIcon/index.tsx
  src/components/atoms/Icon/SellIcon/index.tsx
  src/components/atoms/Icon/XIcon/index.tsx
  src/components/organisms/NeighborhoodSelectionList/index.tsx
  src/components/templates/NeighborhoodSelectionTemplate/index.tsx
  src/components/templates/RootLayout/index.tsx
  src/hooks/useNeighborhoodSelection.ts
  src/hooks/useSearchTopBar.ts
  src/pages/NeighborhoodSelectionPage.tsx
  src/pages/OAuthCallbackPage.tsx
  src/stores/userStore.ts
  src/styles/global.tsx
  yarn.lock
Labels: 🐞 BugFix, 🔨 Refactor

#459 refactor: 검색어 결과(카테고리 검색 결과) 페이지 최적화 작업 (1)
  src/components/organisms/PostList/index.tsx
  src/components/templates/SearchResultsTemplate/index.tsx
  src/constants/SearchResultPageConstants.ts
  src/constants/queryKeys.ts
  src/hooks/useSearchTopBar.ts
  src/pages/SearchResultPage.tsx
  src/services/apis/index.ts
  src/services/apis/post.ts
  src/types/response/index.ts
  src/types/response/post.d.ts
Labels: 🐞 BugFix, 🔨 Refactor

#460 refactor: 검색 페이지 최적화 작업
  public/categorys/AUTOMOTIVE.png
  public/categorys/BEAUTY.png
  public/categorys/BOOKS.png
  public/categorys/CLOTHING.png
  public/categorys/ELECTRONIC.png
  public/categorys/FOOD.png
  public/categorys/FURNITURE.png
  public/categorys/GARDEN.png
  public/categorys/HOME_APPLIANCES.png
  public/categorys/JEWELRY.png
  public/categorys/MUSIC.png
  public/categorys/OFFICE_SUPPLIES.png
  public/categorys/PET_SUPPLIES.png
  public/categorys/SPORTS.png
  public/categorys/TOYS.png
  public/dummy/transaction/1.png
  public/dummy/transaction/2.png
  public/dummy/transaction/3.png
  public/dummy/transaction/4.png
  public/dummy/transaction/5.png
  public/dummy/transaction/6.png
  public/dummy/transaction/7.png
  public/dummy/transaction/8.png
  src/components/molecules/RoundImageWithText/index.tsx
  src/components/organisms/CategoryGrid/index.tsx
  src/components/organisms/SearchHistory/index.tsx
  src/components/templates/SearchTemplate/index.tsx
  src/constants/categories.ts
  src/pages/CategoryPage.tsx
  src/types/category.d.ts
Labels: 🔨 Refactor

#461 refactor: 1:1 채팅방 페이지 최적화 작업
  src/components/atoms/Image/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/AuctionBidBottomSheet/index.tsx
  src/components/organisms/AuctionControlBar/index.tsx
  src/components/organisms/ChatMessages/index.tsx
  src/components/organisms/ChatMessages/styled.ts
  src/components/organisms/PostItem/index.tsx
  src/components/organisms/PostList/index.tsx
  src/components/organisms/PostList/stories.ts
  src/components/organisms/TransactionOverview/index.tsx
  src/components/organisms/TransactionOverview/stories.tsx
  src/components/templates/ChatRoomTemplate/TopSheet.tsx
  src/components/templates/ChatRoomTemplate/index.tsx
  src/components/templates/HomeTemplate/index.tsx
  src/components/templates/HomeTemplate/stories.ts
  src/components/templates/MarketPriceTemplate/index.tsx
  src/components/templates/MarketPriceTemplate/stories.tsx
  src/components/templates/SearchResultsTemplate/index.tsx
  src/components/templates/SearchResultsTemplate/stories.ts
  src/components/templates/TransactionBuyTemplate/index.tsx
  src/components/templates/TransactionBuyTemplate/stories.ts
  src/components/templates/TransactionSellTemplate/index.tsx
  src/components/templates/TransactionSellTemplate/stories.tsx
  src/constants/ChatRoomPageConstants.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useBid.ts
  src/hooks/useChatGroups.ts
  src/hooks/useWebSocket.ts
  src/pages/ChatRoomPage.tsx
  src/pages/DetailPage/index.tsx
  src/pages/HomePage.tsx
  src/pages/MarketPricePage.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/TransactionPage.tsx
  src/types/post.d.ts
  src/types/response/chat.d.ts
  src/types/response/index.ts
  src/utils/index.ts
  src/utils/priceFormatter.ts
Labels: 🔨 Refactor

#394 fix: 상세페이지 엔터 적용안됨 수정
  src/components/organisms/ItemDetails/styled.ts
Labels: 🐞 BugFix

#462 fix: Input Nan 버그 수정
  src/components/organisms/PostItem/index.tsx
  src/hooks/useFetchProduct.ts
  src/utils/priceFormatter.ts
Labels: 🐞 BugFix

#465 refactor: PostRegisterPage에서 useFetchProduct 사용하도록 수정
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/PostRegisterForm/stories.tsx
  src/components/templates/PostRegisterTemplate/index.tsx
  src/components/templates/PostRegisterTemplate/stories.tsx
  src/hooks/useFetchProduct.ts
  src/pages/DetailPage/index.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/SelectLocationPage.tsx
  src/services/apis/product.ts
  src/stores/formDataStore.ts
Labels: 🔨 Refactor

#467 fix: 스크롤 위치를 최상단으로 수정
  src/pages/PrivacyPolicyPage.tsx
  src/pages/TermsOfServicePage.tsx
Labels: 🐞 BugFix

#469 fix: 채팅방 목록 페이지 메인으로 돌아가기 버튼 안보이는 이슈 개선
  src/components/atoms/Logo/styled.ts
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/EmptyTemplate/styled.ts
  src/pages/BlockedUsersPage.tsx
Labels: 🐞 BugFix

#482 fix: 페이지의 스크롤을 일괄 관리로 변경
  src/components/templates/RootLayout/index.tsx
  src/pages/HomePage.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/PrivacyPolicyPage.tsx
  src/pages/TermsOfServicePage.tsx
Labels: 🐞 BugFix
