Repository J1P5/Meerket_FE, pull requests merged in 2025-04, with the labels that each got.

#522 refactor: 물품 등록 form 관련 리팩터링
  package.json
  src/components/atoms/ImageUpload/index.tsx
  src/components/atoms/ImageUpload/stories.ts
  src/components/atoms/Input/index.tsx
  src/components/molecules/UploadedImageCounter/index.tsx
  src/components/molecules/UploadedImageCounter/stories.tsx
  src/components/organisms/PostImageItem/index.tsx
  src/components/organisms/PostImageManager/index.tsx
  src/components/organisms/PostImageManager/styled.ts
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/hooks/index.ts
  src/hooks/useHorizontalScroll.ts
  src/pages/PostRegisterPage.tsx
  src/services/api.ts
  src/styles/zIndexes.ts
  src/types/post.d.ts
  src/utils/file.ts
  src/utils/index.ts
  yarn.lock
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#512 refactor: 지도 관련 코드 리팩터링
  package.json
  src/components/organisms/LocationPicker/index.tsx
  src/components/organisms/LocationPicker/stories.tsx
  src/components/organisms/Map/index.tsx
  src/components/organisms/Map/stories.tsx
  src/components/organisms/NeighborhoodAuthForm/index.tsx
  src/components/organisms/NeighborhoodAuthForm/stories.tsx
  src/components/organisms/UserLocationBottomSheet/index.tsx
  src/components/templates/NeighborhoodAuthTemplate/index.tsx
  src/components/templates/NeighborhoodAuthTemplate/stories.tsx
  src/components/templates/SelectLocationTemplate/index.tsx
  src/components/templates/TransactionLocationTemplate/index.tsx
  src/components/templates/TransactionLocationTemplate/stories.tsx
  src/constants/errorMessage.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useGeolocation.ts
  src/hooks/useLocationErrorEvent.tsx
  src/hooks/useMap.ts
  src/hooks/useReverseGeocode.ts
  src/types/error.d.ts
  src/types/index.ts
  src/types/map.d.ts
  src/utils/index.ts
  src/utils/platform.ts
  yarn.lock
Labels: 🐞 BugFix, 🔨 Refactor

#529 feat: [Next.js] 로그인 페이지 구현
  .gitignore
  apis/api.ts
  apis/auth.ts
  apis/index.ts
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/login/callback/[provider]/page.tsx
  app/login/page.tsx
  app/page.tsx
  components/atoms/LoginButton/index.tsx
  components/atoms/index.ts
  components/templates/LoginTemplate/index.tsx
  components/templates/index.ts
  constants/copy.ts
  constants/index.ts
  next.config.ts
  package.json
  public/LoginButton/kakao.svg
  public/LoginButton/naver.svg
  public/Logo.svg
  public/favicon.ico
  public/firebase-messaging-sw.js
  public/icons/AppIcon.svg
  public/icons/logo-128x128.png
  public/icons/logo-192x192.png
  public/icons/logo-512x512.png
  public/icons/logo-64x64.png
  svgr.d.ts
  tsconfig.json
  types/env.d.ts
  types/index.ts
  types/response/auth.d.ts
  types/response/index.ts
  types/response/response.d.ts
  utils/fcm.ts
  utils/firebase.ts
  utils/index.ts
  yarn.lock
Labels: ✨ Feature, 🏴‍☠️ Next.js

#532 feat: 에러 핸들링 동작 방식 조사
  app/error.tsx
Labels: ✨ Feature
