Repository J1P5/Meerket_FE, pull requests merged in 2025-01, with the labels that each got.

#428 test: 개발서버 LCP 관련 조치 테스트
  package.json
  src/pages/MarketPricePage.tsx
  vite.config.ts
  yarn.lock
Labels: ✅ Test

#429 test: LCP 이미지 크기 관련 테스트
  src/pages/MarketPricePage.tsx
Labels: ✅ Test

#413 refactor: 물품 등록 페이지 피드백 반영
  src/components/molecules/ErrorMessage/index.tsx
  src/components/molecules/ErrorMessage/stories.ts
  src/components/molecules/ErrorMessage/styled.ts
  src/components/molecules/index.ts
  src/components/organisms/PostRegisterForm/index.tsx
  src/pages/PostRegisterPage.tsx
Labels: 🔨 Refactor

#368 feat: HomePage 무한 스크롤 적용
  src/components/templates/HomeTemplate/index.tsx
  src/constants/HomePageConstants.ts
  src/hooks/index.ts
  src/hooks/useScrollRestoration.ts
  src/pages/ChatRoomPage.tsx
  src/pages/HomePage.tsx
  src/pages/PostRegisterPage.tsx
Labels: 🔨 Refactor

#427 refactor: 채팅방 목록 페이지 최적화
  package.json
  src/App.tsx
  src/components/atoms/Toast/stories.tsx
  src/components/organisms/ChatOverview/index.tsx
  src/components/organisms/LocationMap/index.tsx
  src/components/organisms/LocationPicker/index.tsx
  src/components/organisms/NeighborhoodAuthForm/index.tsx
  src/components/templates/ChatListTemplate/index.tsx
  src/components/templates/SelectLocationTemplate/index.tsx
  src/components/templates/TransactionLocationTemplate/index.tsx
  src/constants/Chat.ts
  src/constants/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useBid.ts
  src/hooks/useFetchChatItems.ts
  src/hooks/useNeighborhoodSelection.ts
  src/hooks/useSearchTopBar.ts
  src/pages/BlockedUsersPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/ChatListPage.tsx
  src/pages/ChatRoomPage.tsx
  src/pages/DetailPage/index.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MarketPricePage.tsx
  src/pages/MyPage.tsx
  src/pages/NeighborhoodAuthPage.tsx
  src/pages/NeighborhoodSelectionPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/OAuthCallbackPage.tsx
  src/pages/PermissionRequestPage.tsx
  src/pages/PostRegisterPage.tsx
  src/pages/PrivacyPolicyPage.tsx
  src/pages/ProfileRegistrationPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/SelectLocationPage.tsx
  src/pages/TermsOfServicePage.tsx
  src/pages/TransactionLocationPage.tsx
  src/pages/TransactionPage.tsx
  src/pages/index.ts
  src/router.tsx
  src/services/apis/chat.ts
  src/services/apis/index.ts
  src/styles/global.tsx
  src/types/chat.d.ts
  yarn.lock
Labels: 🔨 Refactor

#433 test: swiper 관련 css 파일 지연 로딩 처리
  src/components/molecules/ImageSlider/index.tsx
Labels: ✅ Test

#440 test: 배포 관련 log 추가
  src/pages/LoginPage.tsx
  src/router.tsx
Labels: ✅ Test

#445 chore: git 프로필 추가
  .github/workflows/develop_deploy.yml
Labels: 🌏 Deploy

#446 chore: deploy.yml 변경
  .github/workflows/develop_deploy.yml
Labels: 🌏 Deploy, ✅ Test

#447 chore: develop_deploy.yml 스크립트 롤백
  .github/workflows/develop_deploy.yml
Labels: 🌏 Deploy, ✅ Test

#448 chore: test 파일 원상복구
  src/App.tsx
  src/pages/MarketPricePage.tsx
  src/router.tsx
Labels: 🌏 Deploy

#449 chore: APP.tsx 원상 복구
  src/main.tsx
Labels: 🌏 Deploy

#450 refactor: Text 컴포넌트 children prop 추가
  src/components/atoms/Badge/index.tsx
  src/components/atoms/Button/TextButton/index.tsx
  src/components/atoms/Text/index.tsx
  src/components/atoms/Text/stories.ts
  src/components/atoms/Text/styled.ts
  src/components/molecules/ErrorMessage/index.tsx
  src/components/molecules/IconWithText/index.tsx
  src/components/molecules/IconWithText_legacy/index.tsx
  src/components/molecules/Loading/index.tsx
  src/components/molecules/ModalBottomSheet/stories.tsx
  src/components/molecules/NavBarItem/index.tsx
  src/components/molecules/RoundImageWithText/index.tsx
  src/components/molecules/TabItem/index.tsx
  src/components/molecules/TextDividerList/index.tsx
  src/components/molecules/TextWithImage/index.tsx
  src/components/molecules/UploadedImageCounter/index.tsx
  src/components/organisms/AuctionBidBottomSheet/index.tsx
  src/components/organisms/AuctionControlBar/index.tsx
  src/components/organisms/AuctionTimer/index.tsx
  src/components/organisms/ChatDay/ChatDay.tsx
  src/components/organisms/ChatItem/index.tsx
  src/components/organisms/ChatMessage/index.tsx
  src/components/organisms/Comment/index.tsx
  src/components/organisms/CommentItem/blocked.tsx
  src/components/organisms/CommentItem/deleted.tsx
  src/components/organisms/CommentItem/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/ItemDetails/index.tsx
  src/components/organisms/LocationInputBottomSheet/index.tsx
  src/components/organisms/LocationMap/index.tsx
  src/components/organisms/LocationPicker/index.tsx
  src/components/organisms/Modal/index.tsx
  src/components/organisms/Modal/stories.tsx
  src/components/organisms/MyPageMenu/index.tsx
  src/components/organisms/NeighborhoodAuthForm/index.tsx
  src/components/organisms/NeighborhoodSelectionList/index.tsx
  src/components/organisms/PermissionList/index.tsx
  src/components/organisms/PostImageItem/index.tsx
  src/components/organisms/PostItem/index.tsx
  src/components/organisms/PostList/index.tsx
  src/components/organisms/PostRegisterForm/index.tsx
  src/components/organisms/Profile/index.tsx
  src/components/organisms/ProfileRegistrationForm/index.tsx
  src/components/organisms/SearchHistory/index.tsx
  src/components/organisms/TopBar/index.tsx
  src/components/organisms/UserLocationBottomSheet/index.tsx
  src/components/templates/ChatRoomTemplate/TopSheet.tsx
  src/components/templates/EmptyTemplate/index.tsx
  src/components/templates/LoginTemplate/index.tsx
  src/components/templates/MyPageTemplate/index.tsx
  src/hooks/useLocationErrorEvent.tsx
  src/hooks/useModalForm.tsx
Labels: 🔨 Refactor
